name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  ##############################
  # 1) INSTALL / BUILD / TEST
  ##############################
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - run: echo "Aucun test"

  ##############################
  # 2) BUILD & PUSH DOCKER IMAGES
  ##############################
  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ### Build & push backend
      - name: Build & push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: spirousl6/backend-app:v1

      ### Build & push frontend
      - name: Build & push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: spirousl6/frontend-app:v1

  ##############################
  # 3) DEPLOY ON KUBERNETES
  ##############################
  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config

      - name: Deploy Backend
        run: |
          kubectl apply -f deploy/backend-deployment.yaml
          kubectl apply -f deploy/backend-service.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f deploy/frontend-deployment.yaml
          kubectl apply -f deploy/frontend-service.yaml
